package egain.oassdk.testgenerators.support;

import egain.oassdk.config.TestConfig;
import egain.oassdk.core.exceptions.GenerationException;
import egain.oassdk.testgenerators.common.TestOutputLayout;
import egain.oassdk.testgenerators.common.TestSpecUtils;

import egain.oassdk.testgenerators.common.TestProfileSupport;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Map;

/**
 * Emits shared test-support Java classes and {@code test-env.properties} template
 * used by all generated Java test modules.
 */
public class TestSupportGenerator {

    public void generate(Map<String, Object> spec, String outputDir, TestConfig config) throws GenerationException {
        generate(spec, outputDir, config, List.of("unit", "integration", "nfr", "performance", "security", "sequence-java"));
    }

    public void generate(Map<String, Object> spec, String outputDir, TestConfig config, List<String> testTypes)
            throws GenerationException {
        try {
            String basePackage = resolvePackage(config);
            String supportPackage = TestOutputLayout.supportPackage(basePackage);
            String defaultBaseUrl = resolveTemplateBaseUrl(spec, config);
            boolean egainAuth = TestSpecUtils.useEgainAuth(config, spec);
            List<String> modules = TestProfileSupport.aggregatorModules(testTypes);

            Path supportDir = Paths.get(TestOutputLayout.supportJavaDir(outputDir, basePackage));
            Files.createDirectories(supportDir);

            write(supportDir.resolve("TestEnv.java"), testEnvSource(supportPackage, defaultBaseUrl));
            write(supportDir.resolve("TestAuth.java"), testAuthSource(supportPackage, egainAuth));
            write(supportDir.resolve("TestHttp.java"), testHttpSource(supportPackage));
            write(supportDir.resolve("TestClient.java"), testClientSource(supportPackage));
            write(supportDir.resolve("TestContext.java"), testContextSource(supportPackage));
            write(supportDir.resolve("RequestBodyEnv.java"), requestBodyEnvSource(supportPackage));
            if (egainAuth) {
                write(supportDir.resolve("EgainAuth.java"), egainAuthSource(supportPackage));
            }

            Path testsRoot = Paths.get(outputDir);
            Files.createDirectories(testsRoot);
            write(testsRoot.resolve("test-env.properties"), testEnvProperties(defaultBaseUrl, egainAuth));
            write(testsRoot.resolve("test-env.local.properties.example"), testEnvLocalExample(egainAuth));
            write(testsRoot.resolve("run-smoke.sh"), runSmokeScript());
            write(testsRoot.resolve("run-smoke.bat"), runSmokeBat());
            write(testsRoot.resolve("run-all.sh"), runAllScript(modules));
            write(testsRoot.resolve("run-all.bat"), runAllBat(modules));
            write(testsRoot.resolve("fetch-token.sh"), fetchTokenScript());
            write(testsRoot.resolve("pom.xml"), aggregatorPom(modules));
            write(testsRoot.resolve("README-TESTS.md"), readmeTests(egainAuth));

        } catch (IOException e) {
            throw new GenerationException("Failed to generate test support: " + e.getMessage(), e);
        }
    }

    private static String resolvePackage(TestConfig config) {
        if (config != null && config.getAdditionalProperties() != null) {
            Object pkg = config.getAdditionalProperties().get("packageName");
            if (pkg != null && !pkg.toString().isBlank()) {
                return pkg.toString().trim();
            }
        }
        return "com.example.api";
    }

    private static String resolveTemplateBaseUrl(Map<String, Object> spec, TestConfig config) {
        String resolved = TestSpecUtils.resolveBaseUrl(spec, config);
        if (resolved == null || resolved.isBlank()) {
            return "";
        }
        if (resolved.contains("${")) {
            return "";
        }
        return resolved;
    }

    private static void write(Path path, String content) throws IOException {
        Files.writeString(path, content, StandardCharsets.UTF_8);
    }

    private static String testEnvSource(String pkg, String defaultBaseUrl) {
        return """
                package %s;

                import java.io.InputStream;
                import java.nio.file.Files;
                import java.nio.file.Path;
                import java.util.Locale;
                import java.util.Properties;

                /**
                 * Loads test-env.properties (+ optional local override) and environment variables.
                 * Generated by OAS SDK TestSupportGenerator.
                 */
                public final class TestEnv {

                    private static final Properties PROPS = loadProperties();

                    private TestEnv() {
                    }

                    private static Properties loadProperties() {
                        Properties p = new Properties();
                        loadFile(p, resolveEnvFile());
                        loadFile(p, siblingFile("test-env.local.properties"));
                        return p;
                    }

                    private static String resolveEnvFile() {
                        String env = System.getenv("TEST_ENV_FILE");
                        if (env != null && !env.isBlank()) {
                            return env.trim();
                        }
                        return siblingPath("test-env.properties");
                    }

                    private static String siblingPath(String name) {
                        Path cwd = Path.of(System.getProperty("user.dir", ".")).toAbsolutePath().normalize();
                        Path parent = cwd.getParent();
                        if (parent != null && Files.isRegularFile(parent.resolve(name))) {
                            return parent.resolve(name).toString();
                        }
                        if (Files.isRegularFile(cwd.resolve(name))) {
                            return cwd.resolve(name).toString();
                        }
                        return name;
                    }

                    private static String siblingFile(String name) {
                        return siblingPath(name);
                    }

                    private static void loadFile(Properties p, String path) {
                        Path file = Path.of(path);
                        if (!Files.isRegularFile(file)) {
                            try (InputStream in = TestEnv.class.getClassLoader().getResourceAsStream(path)) {
                                if (in != null) {
                                    p.load(in);
                                }
                            } catch (Exception ignored) {
                                // optional file
                            }
                            return;
                        }
                        try (InputStream in = Files.newInputStream(file)) {
                            p.load(in);
                        } catch (Exception ignored) {
                            // optional file
                        }
                    }

                    public static String get(String key, String defaultValue) {
                        String envKey = key.toUpperCase(Locale.ROOT).replace('.', '_');
                        String fromEnv = System.getenv(envKey);
                        if (fromEnv != null && !fromEnv.isBlank()) {
                            return fromEnv.trim();
                        }
                        String fromProp = PROPS.getProperty(key);
                        if (fromProp != null && !fromProp.isBlank()) {
                            return fromProp.trim();
                        }
                        return defaultValue;
                    }

                    public static boolean getBoolean(String key, boolean defaultValue) {
                        String v = get(key, null);
                        if (v == null) {
                            return defaultValue;
                        }
                        return "true".equalsIgnoreCase(v) || "1".equals(v);
                    }

                    public static int getInt(String key, int defaultValue) {
                        String v = get(key, null);
                        if (v == null) {
                            return defaultValue;
                        }
                        try {
                            return Integer.parseInt(v.trim());
                        } catch (NumberFormatException e) {
                            return defaultValue;
                        }
                    }

                    public static String baseUrl() {
                        String env = System.getenv("API_BASE_URL");
                        if (env != null && !env.isBlank()) {
                            return env.trim();
                        }
                        return get("base.url", "%s");
                    }

                    public static String acceptLanguage() {
                        return get("accept.language", "en-US");
                    }

                    public static String departmentId() {
                        return get("test.department.id", "1");
                    }

                    public static String parentFolderId() {
                        return get("test.parent.folder.id", get("test.filter.parent.id", "1"));
                    }

                    public static String folderId() {
                        return get("test.folder.id", parentFolderId());
                    }

                    public static String hierarchyRootFolderId() {
                        return get("test.hierarchy.root.folder.id", get("test.filter.parent.id", parentFolderId()));
                    }

                    public static String userId() {
                        return get("test.user.id", "1");
                    }

                    public static String userGroupId() {
                        return get("test.user.group.id", "1");
                    }

                    public static String promptId() {
                        return get("test.prompt.id", "1");
                    }

                    public static String loginBase() {
                        return get("auth.login.base", get("auth.login.url", ""));
                    }

                    public static String exchangePath() {
                        return get("auth.exchange.path", "/authentication/user/advisor/oauth2/token");
                    }

                    public static String schemathesisIncludeOperations() {
                        return get("schemathesis.include.operations",
                                "createFolder,getSubFolders,editFolder,getFolder");
                    }

                    public static String pageNum() {
                        return String.valueOf(getInt("test.pagination.pageNum", 1));
                    }

                    public static String pageSize() {
                        return String.valueOf(getInt("test.pagination.pageSize", 10));
                    }

                    public static boolean tlsVerify() {
                        return getBoolean("tls.verify", true);
                    }

                    public static boolean bootstrapEnabled() {
                        return getBoolean("test.bootstrap.enabled", false);
                    }

                    public static boolean destructiveEnabled() {
                        return getBoolean("test.destructive.enabled", false);
                    }

                    public static boolean validateResponseSchema() {
                        return getBoolean("test.validateResponseSchema", false);
                    }
                }
                """.formatted(pkg, escapeJava(defaultBaseUrl));
    }

    private static String testAuthSource(String pkg, boolean egainAuth) {
        String egainCall = egainAuth
                ? """
                        String egain = EgainAuth.fetchBearerToken();
                        if (egain != null && !egain.isBlank()) {
                            cacheToken(egain);
                            return egain;
                        }
                        """
                : "";
        return """
                package %s;

                /**
                 * Resolves bearer token: env override, property file, optional eGain login.
                 */
                public final class TestAuth {

                    private static volatile String cachedToken;

                    private TestAuth() {
                    }

                    public static void clearCache() {
                        cachedToken = null;
                    }

                    public static String rawToken() {
                        if (cachedToken != null && !cachedToken.isBlank()) {
                            return cachedToken;
                        }
                        String t = System.getenv("API_TOKEN");
                        if (t != null && !t.isBlank()) {
                            return t.trim();
                        }
                        t = System.getenv("API_BEARER_TOKEN");
                        if (t != null && !t.isBlank()) {
                            return t.trim();
                        }
                        t = System.getenv("INTEGRATION_TOKEN_CLIENT_APPLICATION");
                        if (t != null && !t.isBlank()) {
                            return t.trim();
                        }
                        t = TestEnv.get("auth.token", null);
                        if (t != null && !t.isBlank()) {
                            cachedToken = t.trim();
                            return cachedToken;
                        }
                        %s
                        return "";
                    }

                    public static void cacheToken(String token) {
                        if (token != null && !token.isBlank()) {
                            cachedToken = token.trim();
                        }
                    }

                    public static String bearerHeader() {
                        String t = rawToken();
                        return t.isEmpty() ? "" : "Bearer " + t;
                    }
                }
                """.formatted(pkg, egainCall);
    }

    private static String testHttpSource(String pkg) {
        return """
                package %s;

                import javax.net.ssl.SSLContext;
                import javax.net.ssl.TrustManager;
                import javax.net.ssl.X509TrustManager;
                import java.net.http.HttpClient;
                import java.security.cert.X509Certificate;
                import java.time.Duration;

                public final class TestHttp {

                    private TestHttp() {
                    }

                    public static HttpClient client() {
                        HttpClient.Builder builder = HttpClient.newBuilder()
                                .connectTimeout(Duration.ofSeconds(30));
                        if (!TestEnv.tlsVerify()) {
                            try {
                                TrustManager[] trustAll = new TrustManager[]{
                                        new X509TrustManager() {
                                            public void checkClientTrusted(X509Certificate[] c, String a) {}
                                            public void checkServerTrusted(X509Certificate[] c, String a) {}
                                            public X509Certificate[] getAcceptedIssuers() { return new X509Certificate[0]; }
                                        }
                                };
                                SSLContext ssl = SSLContext.getInstance("TLS");
                                ssl.init(null, trustAll, new java.security.SecureRandom());
                                builder.sslContext(ssl);
                            } catch (Exception e) {
                                throw new RuntimeException("Failed to configure TLS trust", e);
                            }
                        }
                        return builder.build();
                    }
                }
                """.formatted(pkg);
    }

    private static String testClientSource(String pkg) {
        return """
                package %s;

                import io.restassured.RestAssured;
                import io.restassured.specification.RequestSpecification;

                import static io.restassured.RestAssured.given;

                public final class TestClient {

                    private TestClient() {
                    }

                    public static void configureRestAssured() {
                        RestAssured.baseURI = TestEnv.baseUrl();
                        RestAssured.useRelaxedHTTPSValidation();
                    }

                    public static RequestSpecification givenAuth() {
                        RequestSpecification spec = given()
                                .header("Accept", "application/json")
                                .header("Accept-Language", TestEnv.acceptLanguage());
                        String token = TestAuth.rawToken();
                        if (token != null && !token.isEmpty()) {
                            spec = spec.header("Authorization", "Bearer " + token);
                        }
                        return spec;
                    }
                }
                """.formatted(pkg);
    }

    private static String testContextSource(String pkg) {
        return """
                package %s;

                import java.util.ArrayList;
                import java.util.Collections;
                import java.util.List;
                import java.util.concurrent.CopyOnWriteArrayList;

                /** Shared state for workflow and lifecycle tests. */
                public final class TestContext {

                    private static final CopyOnWriteArrayList<String> CREATED_IDS = new CopyOnWriteArrayList<>();
                    private static volatile String bootstrapParentFolderId;
                    private static volatile String bootstrapHierarchyRootId;
                    private static volatile String disposableFolderId;

                    private TestContext() {
                    }

                    public static void trackCreatedId(String id) {
                        if (id != null && !id.isBlank()) {
                            CREATED_IDS.add(id);
                        }
                    }

                    public static List<String> createdIds() {
                        return Collections.unmodifiableList(new ArrayList<>(CREATED_IDS));
                    }

                    public static void clearCreatedIds() {
                        CREATED_IDS.clear();
                    }

                    public static String bootstrapParentFolderId() {
                        return bootstrapParentFolderId;
                    }

                    public static void setBootstrapParentFolderId(String id) {
                        bootstrapParentFolderId = id;
                    }

                    public static String bootstrapHierarchyRootId() {
                        return bootstrapHierarchyRootId;
                    }

                    public static void setBootstrapHierarchyRootId(String id) {
                        bootstrapHierarchyRootId = id;
                    }

                    public static String disposableFolderId() {
                        return disposableFolderId;
                    }

                    public static void setDisposableFolderId(String id) {
                        disposableFolderId = id;
                    }
                }
                """.formatted(pkg);
    }

    private static String requestBodyEnvSource(String pkg) {
        return """
                package %s;

                /**
                 * Binds request JSON bodies to {@link TestEnv} at runtime (parent folder, user IDs, etc.).
                 */
                public final class RequestBodyEnv {

                    private RequestBodyEnv() {
                    }

                    public static String bind(String json) {
                        if (json == null || json.isBlank()) {
                            return json;
                        }
                        String bound = json;
                        bound = bound.replace("${test.parent.folder.id}", TestEnv.parentFolderId());
                        bound = bound.replace("${test.filter.parent.id}", TestEnv.get("test.filter.parent.id", TestEnv.parentFolderId()));
                        bound = bound.replace("${test.user.id}", TestEnv.userId());
                        bound = bound.replace("${test.user.group.id}", TestEnv.userGroupId());
                        bound = bound.replace("${test.department.id}", TestEnv.departmentId());
                        bound = replaceParentId(bound, TestEnv.parentFolderId());
                        if (!bound.contains("\\"name\\"") && bound.contains("createFolder")) {
                            bound = bound.replaceFirst("\\{", "{\\"name\\":\\"SDK-generated-folder\\",");
                        }
                        return bound;
                    }

                    private static String replaceParentId(String json, String parentId) {
                        if (parentId == null || parentId.isBlank()) {
                            return json;
                        }
                        return json.replaceAll(
                                "\\"parent\\"\\\\s*:\\\\s*\\\\{[^}]*\\\\"id\\\\"\\\\s*:\\\\s*\\\\\\"[^\\\\\\"]*\\\\\\"",
                                "\\"parent\\":{\\"id\\":\\"" + parentId + "\\"}");
                    }
                }
                """.formatted(pkg);
    }

    private static String egainAuthSource(String pkg) {
        return """
                package %s;

                import java.net.URI;
                import java.net.http.HttpClient;
                import java.net.http.HttpRequest;
                import java.net.http.HttpResponse;
                import java.time.Duration;

                /**
                 * eGain v20 session login + advisor OAuth2 bearer exchange.
                 * Configure auth.login.base, auth.username, auth.password in test-env.properties.
                 */
                public final class EgainAuth {

                    private EgainAuth() {
                    }

                    public static String fetchBearerToken() {
                        String username = TestEnv.get("auth.username", null);
                        String password = TestEnv.get("auth.password", null);
                        if (username == null || password == null || username.isBlank() || password.isBlank()) {
                            return null;
                        }
                        String loginBase = TestEnv.loginBase();
                        if (loginBase == null || loginBase.isBlank()) {
                            return null;
                        }
                        try {
                            HttpClient client = TestHttp.client();
                            String loginUrl = loginBase.endsWith("/")
                                    ? loginBase + "authentication/user/login"
                                    : loginBase + "/authentication/user/login";
                            String sessionBody = "{\\"username\\":\\"" + escapeJson(username)
                                    + "\\",\\"password\\":\\"" + escapeJson(password) + "\\"}";
                            HttpRequest login = HttpRequest.newBuilder()
                                    .uri(URI.create(loginUrl))
                                    .timeout(Duration.ofSeconds(30))
                                    .header("Content-Type", "application/json")
                                    .header("Accept", "application/json")
                                    .POST(HttpRequest.BodyPublishers.ofString(sessionBody))
                                    .build();
                            HttpResponse<String> loginResp = client.send(login, HttpResponse.BodyHandlers.ofString());
                            if (loginResp.statusCode() >= 300) {
                                System.err.println("EgainAuth: login failed HTTP " + loginResp.statusCode());
                                return null;
                            }
                            String sessionId = loginResp.headers().firstValue("X-egain-session").orElse(null);
                            if (sessionId == null) {
                                sessionId = extractJsonString(loginResp.body(), "sessionId");
                            }
                            if (sessionId == null) {
                                return null;
                            }
                            String exchangePath = TestEnv.exchangePath();
                            String exchangeUrl = loginBase.endsWith("/")
                                    ? loginBase.substring(0, loginBase.length() - 1) + exchangePath
                                    : loginBase + exchangePath;
                            HttpRequest exchange = HttpRequest.newBuilder()
                                    .uri(URI.create(exchangeUrl))
                                    .timeout(Duration.ofSeconds(30))
                                    .header("Accept", "application/json")
                                    .header("X-egain-session", sessionId)
                                    .GET()
                                    .build();
                            HttpResponse<String> exchangeResp = client.send(exchange, HttpResponse.BodyHandlers.ofString());
                            if (exchangeResp.statusCode() >= 300) {
                                System.err.println("EgainAuth: exchange failed HTTP " + exchangeResp.statusCode());
                                return null;
                            }
                            String bearer = extractJsonString(exchangeResp.body(), "access_token");
                            if (bearer == null) {
                                bearer = extractJsonString(exchangeResp.body(), "token");
                            }
                            if (bearer != null) {
                                TestAuth.cacheToken(bearer);
                            }
                            return bearer;
                        } catch (Exception e) {
                            System.err.println("EgainAuth: " + e.getMessage());
                            return null;
                        }
                    }

                    private static String extractJsonString(String json, String field) {
                        if (json == null) {
                            return null;
                        }
                        String needle = "\\"" + field + "\\":\\"";
                        int i = json.indexOf(needle);
                        if (i < 0) {
                            return null;
                        }
                        int start = i + needle.length();
                        int end = json.indexOf('"', start);
                        return end > start ? json.substring(start, end) : null;
                    }

                    private static String escapeJson(String s) {
                        return s.replace("\\\\", "\\\\\\\\").replace("\\"", "\\\\\\"");
                    }
                }
                """.formatted(pkg);
    }

    private static String testEnvProperties(String defaultBaseUrl, boolean egainAuth) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated test environment — copy test-env.local.properties.example for secrets\n");
        if (defaultBaseUrl == null || defaultBaseUrl.isBlank()) {
            sb.append("# base.url must include /system/ws/... for eGain authoring hosts\n");
            sb.append("base.url=\n");
        } else {
            sb.append("base.url=").append(defaultBaseUrl).append("\n");
        }
        sb.append("accept.language=en-US\n");
        sb.append("tls.verify=false\n\n");
        sb.append("# Test data IDs (discover via GET /folders?departmentId=...)\n");
        sb.append("test.department.id=\n");
        sb.append("test.parent.folder.id=\n");
        sb.append("test.filter.parent.id=\n");
        sb.append("test.hierarchy.root.folder.id=\n");
        sb.append("test.folder.id=\n");
        sb.append("test.user.id=\n");
        sb.append("test.user.group.id=\n");
        sb.append("test.prompt.id=\n\n");
        sb.append("test.pagination.pageNum=1\n");
        sb.append("test.pagination.pageSize=10\n\n");
        sb.append("test.bootstrap.enabled=false\n");
        sb.append("test.destructive.enabled=false\n");
        sb.append("test.validateResponseSchema=false\n\n");
        sb.append("schemathesis.include.operations=createFolder,getSubFolders,editFolder,getFolder\n\n");
        sb.append("# Auth — optional manual token (CI secret store)\n");
        sb.append("auth.token=\n");
        if (egainAuth) {
            sb.append("auth.provider=egain\n");
            sb.append("auth.login.base=\n");
            sb.append("auth.exchange.path=/authentication/user/advisor/oauth2/token\n");
            sb.append("auth.username=\n");
            sb.append("auth.password=\n");
        }
        return sb.toString();
    }

    private static String testEnvLocalExample(boolean egainAuth) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Local overrides — do not commit\n");
        sb.append("base.url=https://YOUR-HOST/system/ws/knowledge/contentmgr/v4\n");
        sb.append("accept.language=en-US\n");
        sb.append("tls.verify=false\n\n");
        if (egainAuth) {
            sb.append("auth.login.base=https://YOUR-HOST/system/ws/v20\n");
            sb.append("auth.username=your-user\n");
            sb.append("auth.password=CHANGE_ME\n");
        }
        sb.append("test.department.id=1001\n");
        sb.append("test.parent.folder.id=\n");
        sb.append("test.filter.parent.id=\n");
        sb.append("test.hierarchy.root.folder.id=\n");
        sb.append("test.folder.id=\n");
        sb.append("test.user.id=\n");
        sb.append("test.user.group.id=\n");
        sb.append("test.bootstrap.enabled=false\n");
        sb.append("test.destructive.enabled=false\n");
        return sb.toString();
    }

    private static String runSmokeScript() {
        return """
                #!/usr/bin/env bash
                set -euo pipefail
                ROOT="$(cd "$(dirname "$0")" && pwd)"
                export TEST_ENV_FILE="${TEST_ENV_FILE:-$ROOT/test-env.properties}"
                cd "$ROOT/unit"
                mvn -q test -Dtest='FoldersApiTest#testGetSubFolders_ValidRequest' || true
                cd "$ROOT/integration"
                mvn -q test -Dtest='FoldersIntegrationTest#testGetSubFolders_Success_ClientApplication' || true
                echo "Smoke tests finished (see output above)."
                """;
    }

    private static String runSmokeBat() {
        return """
                @echo off
                set ROOT=%~dp0
                if not defined TEST_ENV_FILE set TEST_ENV_FILE=%ROOT%test-env.properties
                cd /d %ROOT%unit
                call mvn -q test -Dtest=FoldersApiTest#testGetSubFolders_ValidRequest
                cd /d %ROOT%integration
                call mvn -q test -Dtest=FoldersIntegrationTest#testGetSubFolders_Success_ClientApplication
                echo Smoke tests finished.
                """;
    }

    private static String aggregatorPom(List<String> modules) {
        StringBuilder moduleXml = new StringBuilder();
        for (String module : modules) {
            moduleXml.append("        <module>").append(module).append("</module>\n");
        }
        return """
                <?xml version="1.0" encoding="UTF-8"?>
                <project xmlns="http://maven.apache.org/POM/4.0.0"
                         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>com.example.api</groupId>
                    <artifactId>generated-api-tests</artifactId>
                    <version>1.0.0</version>
                    <packaging>pom</packaging>
                    <modules>
                __MODULES__    </modules>
                </project>
                """.replace("__MODULES__", moduleXml.toString());
    }

    private static String runAllScript(List<String> modules) {
        String mvnModules = String.join(",", modules);
        return """
                #!/usr/bin/env bash
                set -euo pipefail
                ROOT="$(cd "$(dirname "$0")" && pwd)"
                export TEST_ENV_FILE="${TEST_ENV_FILE:-$ROOT/test-env.properties}"
                if [[ -f "$ROOT/test-env.local.properties" ]]; then
                  set -a
                  # shellcheck disable=SC1091
                  source "$ROOT/test-env.local.properties"
                  set +a
                fi
                PROFILE="${TEST_PROFILE:-full}"
                echo "Running test profile: $PROFILE"
                ./run-smoke.sh
                if [[ "$PROFILE" != "smoke" ]]; then
                  mvn -q test -pl __MVN_MODULES__
                else
                  mvn -q test -pl integration
                fi
                if [[ -d "$ROOT/schemathesis" && -x "$ROOT/schemathesis/run-schemathesis.sh" ]]; then
                  (cd "$ROOT/schemathesis" && ./run-schemathesis.sh) || true
                fi
                if [[ -x "$ROOT/run-tests.sh" ]]; then
                  ./run-tests.sh || true
                fi
                echo "run-all finished."
                """.replace("__MVN_MODULES__", mvnModules);
    }

    private static String runAllBat(List<String> modules) {
        String mvnModules = String.join(",", modules);
        return """
                @echo off
                set ROOT=%~dp0
                if not defined TEST_ENV_FILE set TEST_ENV_FILE=%ROOT%test-env.properties
                if not defined TEST_PROFILE set TEST_PROFILE=full
                call %ROOT%run-smoke.bat
                if /I "%TEST_PROFILE%"=="smoke" (
                  cd /d %ROOT%integration
                  call mvn -q test
                ) else (
                  cd /d %ROOT%
                  call mvn -q test -pl __MVN_MODULES__
                )
                echo run-all finished.
                """.replace("__MVN_MODULES__", mvnModules);
    }

    private static String fetchTokenScript() {
        return """
                #!/usr/bin/env bash
                set -euo pipefail
                ROOT="$(cd "$(dirname "$0")" && pwd)"
                export TEST_ENV_FILE="${TEST_ENV_FILE:-$ROOT/test-env.properties}"
                cd "$ROOT/unit"
                mvn -q -DincludeScope=test -DskipTests compile test-compile
                TOKEN=$(java -cp "target/test-classes:target/classes:$ROOT/test-support/target/test-classes" \\
                  -Dtest.env.file="$TEST_ENV_FILE" \\
                  com.example.api.support.EgainAuth 2>/dev/null || true)
                if [[ -n "${TOKEN:-}" ]]; then
                  echo "TOKEN='Bearer $TOKEN'"
                else
                  echo "Could not fetch token — set auth.username/auth.password in test-env.local.properties" >&2
                  exit 1
                fi
                """;
    }

    private static String readmeTests(boolean egainAuth) {
        return """
                # Generated API Tests

                ## Quick start

                1. Copy `test-env.local.properties.example` to `test-env.local.properties` and fill in values.
                2. Run all suites: `./run-all.sh` (or `run-all.bat` on Windows).
                3. Smoke only: `./run-smoke.sh`.
                4. Profile `smoke`: `TEST_PROFILE=smoke ./run-all.sh` (integration + schemathesis, no unit matrix).

                ## Configuration

                All Java test modules load `test-env.properties` via `TestEnv`. Environment variables override properties.

                Key properties: `base.url`, `test.department.id`, `test.parent.folder.id`, `test.hierarchy.root.folder.id`, `accept.language`.

                ## Suite overlap

                | Suite | Role |
                |-------|------|
                | Integration (JUnit) | Business scenarios, bootstrap, create→verify |
                | Unit (RestAssured) | Contract/param matrix against live API |
                | Schemathesis | Contract fuzz / property-based exploration |
                | Postman/Newman | Manual collection replay |

                Use `TEST_PROFILE=smoke` to reduce duplicate coverage between unit and integration.
                """
                + (egainAuth
                ? "\n\neGain auth: set `auth.login.base`, `auth.username`, `auth.password` — no manual JWT copy needed.\n"
                : "\n\nSet `auth.token` or export `API_TOKEN` for bearer auth.\n");
    }

    private static String escapeJava(String s) {
        if (s == null) {
            return "";
        }
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
